import React from 'react';
import assert from 'node:assert/strict';
import test from 'node:test';
import {PassThrough} from 'node:stream';
import {render} from 'ink-testing-library';
import {App} from '../src/ui/App.js';
import {editor} from '../src/state/editor.js';
import {TuiController} from '../src/state/controller.js';
import {RuntimeClient} from '../src/protocol/client.js';
import {RpcPeer} from '../src/protocol/peer.js';
import {until} from './helpers.js';

test('arrows edit multiline drafts and input history restores text, cursor and attachments', async t => {
  const c = new TuiController(new RuntimeClient(new RpcPeer(new PassThrough(), new PassThrough())));
  t.after(() => {c.dispose(); c.client.peer.close();});
  c.history.entries.push('first question', 'second question');
  c.composer = {...editor('first line\nsecond line [Image #1]'), cursor: 3};
  c.images = [{label: '[Image #1]', image: {attachment_id: 'image', variant_id: 'v', mime_type: 'image/png', width: 1, height: 1, size_bytes: 100, original_width: 1, original_height: 1, name: 'test.png', turn_id: null}}];
  const draft = c.composer, images = c.images;
  await c.key('', {upArrow: true});
  assert.equal(c.composer, draft, 'top-row Up must not load history');
  await c.key('', {downArrow: true});
  assert.equal(c.composer.cursor, 14);
  await c.key('', {upArrow: true});
  const saved = c.composer;
  await c.key('', {upArrow: true, meta: true});
  assert.equal(c.composer.text, 'second question');
  assert.deepEqual(c.images, []);
  c.wheel(-3);
  assert.equal(c.composer.text, 'second question');
  await c.key('', {upArrow: true});
  assert.equal(c.composer.text, 'first question');
  await c.key('', {downArrow: true});
  await c.key('', {downArrow: true});
  assert.deepEqual(c.composer, saved);
  assert.deepEqual(c.images, images);
  await c.key('c', {ctrl: true});
  await c.key('', {upArrow: true});
  assert.equal(c.composer.text, 'second question', 'empty input recalls history');
  await c.key('!', {});
  await c.key('', {upArrow: true});
  assert.equal(c.composer.text, 'second question!', 'editing a recalled entry resumes normal cursor navigation');
  assert.deepEqual(c.history.entries, ['first question', 'second question']);
});

test('real terminal wheel reports never become history navigation or draft text', async t => {
  const c = new TuiController(new RuntimeClient(new RpcPeer(new PassThrough(), new PassThrough())));
  c.session.connected = true;
  c.history.entries.push('previous question');
  c.composer = editor('unfinished draft');
  c.session.add('user', 'You', Array.from({length: 100}, (_, i) => `line ${i}`).join('\n'));
  const app = render(<App controller={c}/>);
  t.after(() => {app.cleanup(); c.dispose(); c.client.peer.close();});
  await until(() => app.lastFrame()?.includes('line 99'));
  const draft = c.composer;
  app.stdin.write('\x1b[<64;10;10M');
  await until(() => c.offset !== null);
  assert.equal(c.composer, draft);
  app.stdin.write('\x1b[<0;10;10M\x1b[<0;10;10m\x1b[<66;10;10M');
  assert.equal(c.composer, draft, 'click, release and horizontal wheel do not edit');
  app.stdin.write('\x1b[<65;10;10M');
  await until(() => c.offset === null);
  c.document('Details', Array.from({length: 100}, (_, i) => `detail ${i}`).join('\n'));
  await until(() => app.lastFrame()?.includes('Details'));
  const screen = c.screen;
  assert(screen?.kind === 'document');
  app.stdin.write('\x1b[<64;10;10M\x1b[<65;10;10M');
  await until(() => screen.offset > 0);
  assert.equal(c.offset, null, 'a modal owns wheel scrolling');
  assert.equal(c.composer, draft);
  app.stdin.write('\x1b');
  await until(() => !c.screen);
  app.stdin.write('\x1b[200~[<64;10;10M\x1b[201~');
  await until(() => c.composer.text.endsWith('[<64;10;10M'));
});
