import React from 'react';
import assert from 'node:assert/strict';
import test from 'node:test';
import {PassThrough} from 'node:stream';
import {render} from 'ink-testing-library';
import {App} from '../src/ui/App.js';
import {editor} from '../src/state/editor.js';
import {TuiController} from '../src/state/controller.js';
import {RuntimeClient} from '@reuleauxcoder/client';
import {RpcPeer} from '@reuleauxcoder/client/node';
import {until} from './helpers.js';
import {panelRows} from '../src/ui/panels.js';
import {safe} from '../src/ui/format.js';

test('reading anchors survive new output, detail changes and resize until explicitly resumed', async t => {
  const c = new TuiController(new RuntimeClient(new RpcPeer(new PassThrough(), new PassThrough())));
  c.session.connected = true;
  for (let i = 0; i < 30; i++) c.session.add('user', 'You', `Message ${i}\n` + 'body\n'.repeat(3));
  const app = render(<App controller={c}/>);
  t.after(() => {app.cleanup(); c.dispose(); c.client.peer.close();});
  await until(() => app.lastFrame()?.includes('Message 29'));
  await c.key('', {pageUp: true});
  await until(() => app.lastFrame()?.includes('History '));
  const before = c.offset;
  const anchor = safe(app.lastFrame()!).match(/Message \d+/)?.[0];
  assert(anchor);
  c.session.add('assistant', 'Reuleaux', 'New response'); c.changed();
  await until(() => app.lastFrame()?.includes('New output'));
  assert.equal(c.offset, before);
  assert(safe(app.lastFrame()!).includes(anchor));
  c.toggleDetails();
  await until(() => c.expanded);
  c.resize(100, 90);
  await until(() => app.lastFrame()?.includes('Ctrl+End'));
  assert.notEqual(c.offset, null);
  assert(safe(app.lastFrame()!).includes(anchor));
  await c.key('', {ctrl: true, end: true});
  assert.equal(c.offset, null);
  assert.equal(c.hasNewOutput, false);
  await until(() => app.lastFrame()?.includes('New response'));
});

test('choice prompts scroll without changing the answer or the underlying draft', async t => {
  const c = new TuiController(new RuntimeClient(new RpcPeer(new PassThrough(), new PassThrough())));
  t.after(() => {c.dispose(); c.client.peer.close();});
  c.composer = editor('preserved draft');
  c.client.interactions.push({kind: 'choose_one', request: {request_id: 'choice', title: 'Choose', message: '', allow_cancel: true, items: Array.from({length: 20}, (_, i) => ({id: String(i), label: `Choice ${i}`}))}, expiresAt: null, resolve() {}});
  const active = c.active!;
  panelRows(c, 60, 6);
  c.wheel(12);
  await until(() => c.selection(active).offset === 12);
  assert.equal(c.interactionIndex, 0);
  assert(safe(panelRows(c, 60, 6)!.rows.join('\n')).includes('Choice 6'));
  await c.key('', {return: true});
  assert.equal(c.active, active);
  assert(safe(panelRows(c, 60, 6)!.rows.join('\n')).includes('Choice 0'));
  assert.equal(c.composer.text, 'preserved draft');
  assert.equal(c.offset, null);
  await c.key('', {upArrow: true});
  assert.equal(c.interactionIndex, 0);
});

test('list wheel/pages preserve selection and Enter reveals offscreen actions before activating', async t => {
  const c = new TuiController(new RuntimeClient(new RpcPeer(new PassThrough(), new PassThrough())));
  t.after(() => {c.dispose(); c.client.peer.close();});
  const selected: number[] = [];
  c.screens.push({kind: 'list', title: 'Options', index: 0, filter: editor(), items: Array.from({length: 40}, (_, i) => ({label: `Option ${i}`, description: '', select: () => {selected.push(i);}}))});
  const screen = c.screen!;
  assert(screen.kind === 'list');
  const view = () => safe(panelRows(c, 60, 8)!.rows.join('\n'));
  assert(view().includes('Option 0'));
  c.wheel(20);
  await until(() => c.selection(screen).offset === 20);
  assert(view().includes('Option 10'));
  assert.equal(screen.index, 0);
  await c.key('', {return: true});
  assert.deepEqual(selected, []);
  assert(view().includes('Option 0'));
  await c.key('', {return: true});
  assert.deepEqual(selected, [0]);
  await c.key('', {upArrow: true});
  assert.equal(screen.index, 0, 'no wrap at the first item');
  c.viewportRows = 8;
  await c.key('', {pageDown: true});
  await until(() => c.selection(screen).offset === 7);
  assert.equal(screen.index, 0);
  await c.key('', {downArrow: true});
  assert.equal(screen.index, 1);
  assert(view().includes('Option 1'), 'keyboard selection becomes visible again');
  assert.equal(c.offset, null, 'panel navigation does not move the transcript');
});

test('arrows edit multiline drafts and input history restores text, cursor and attachments', async t => {
  const c = new TuiController(new RuntimeClient(new RpcPeer(new PassThrough(), new PassThrough())));
  t.after(() => {c.dispose(); c.client.peer.close();});
  c.history.entries.push('first question', 'second question');
  c.composer = {...editor('first line\nsecond line [Image #1]'), cursor: 3};
  c.images = [{label: '[Image #1]', image: {attachment_id: 'image', variant_id: 'v', mime_type: 'image/png', width: 1, height: 1, size_bytes: 100, original_width: 1, original_height: 1, name: 'test.png', turn_id: null}}];
  const draft = c.composer, images = c.images;
  await c.key('', {upArrow: true});
  assert.equal(c.composer, draft, 'top-row Up must not load history');
  await c.key('', {downArrow: true});
  assert.equal(c.composer.cursor, 14);
  await c.key('', {upArrow: true});
  const saved = c.composer;
  await c.key('', {upArrow: true, meta: true});
  assert.equal(c.composer.text, 'second question');
  assert.deepEqual(c.images, []);
  c.wheel(-3);
  assert.equal(c.composer.text, 'second question');
  await c.key('', {upArrow: true});
  assert.equal(c.composer.text, 'first question');
  await c.key('', {downArrow: true});
  await c.key('', {downArrow: true});
  assert.deepEqual(c.composer, saved);
  assert.deepEqual(c.images, images);
  await c.key('c', {ctrl: true});
  await c.key('', {upArrow: true});
  assert.equal(c.composer.text, 'second question', 'empty input recalls history');
  await c.key('!', {});
  await c.key('', {upArrow: true});
  assert.equal(c.composer.text, 'second question!', 'editing a recalled entry resumes normal cursor navigation');
  assert.deepEqual(c.history.entries, ['first question', 'second question']);
});

test('real terminal wheel reports never become history navigation or draft text', async t => {
  const c = new TuiController(new RuntimeClient(new RpcPeer(new PassThrough(), new PassThrough())));
  c.session.connected = true;
  c.history.entries.push('previous question');
  c.composer = editor('unfinished draft');
  c.session.add('user', 'You', Array.from({length: 100}, (_, i) => `line ${i}`).join('\n'));
  const app = render(<App controller={c}/>);
  t.after(() => {app.cleanup(); c.dispose(); c.client.peer.close();});
  await until(() => app.lastFrame()?.includes('line 99'));
  const draft = c.composer;
  app.stdin.write('\x1b[<64;10;10M');
  await until(() => c.offset !== null);
  assert.equal(c.composer, draft);
  app.stdin.write('\x1b[<0;10;10M\x1b[<0;10;10m\x1b[<66;10;10M');
  assert.equal(c.composer, draft, 'click, release and horizontal wheel do not edit');
  app.stdin.write('\x1b[<65;10;10M');
  await until(() => c.offset === null);
  c.document('Details', Array.from({length: 100}, (_, i) => `detail ${i}`).join('\n'));
  await until(() => app.lastFrame()?.includes('Details'));
  const screen = c.screen;
  assert(screen?.kind === 'document');
  app.stdin.write('\x1b[<64;10;10M\x1b[<65;10;10M');
  await until(() => screen.offset > 0);
  assert.equal(c.offset, null, 'a modal owns wheel scrolling');
  assert.equal(c.composer, draft);
  app.stdin.write('\x1b');
  await until(() => !c.screen);
  app.stdin.write('\x1b[200~[<64;10;10M\x1b[201~');
  await until(() => c.composer.text.endsWith('[<64;10;10M'));
});
