import React from 'react';
import assert from 'node:assert/strict';
import test from 'node:test';
import {PassThrough} from 'node:stream';
import {render} from 'ink-testing-library';
import {App} from '../src/ui/App.js';
import {editor} from '../src/state/editor.js';
import {TuiController} from '../src/state/controller.js';
import {RuntimeClient} from '../src/protocol/client.js';
import {RpcPeer} from '../src/protocol/peer.js';
import {until} from './helpers.js';

test('real terminal wheel reports never become history navigation or draft text', async t => {
  const c = new TuiController(new RuntimeClient(new RpcPeer(new PassThrough(), new PassThrough())));
  c.session.connected = true;
  c.history.entries.push('previous question');
  c.composer = editor('unfinished draft');
  c.session.add('user', 'You', Array.from({length: 100}, (_, i) => `line ${i}`).join('\n'));
  const app = render(<App controller={c}/>);
  t.after(() => {app.cleanup(); c.dispose(); c.client.peer.close();});
  await until(() => app.lastFrame()?.includes('line 99'));
  const draft = c.composer;
  app.stdin.write('\x1b[<64;10;10M');
  await until(() => c.offset !== null);
  assert.equal(c.composer, draft);
  app.stdin.write('\x1b[<0;10;10M\x1b[<0;10;10m\x1b[<66;10;10M');
  assert.equal(c.composer, draft, 'click, release and horizontal wheel do not edit');
  app.stdin.write('\x1b[<65;10;10M');
  await until(() => c.offset === null);
  c.document('Details', Array.from({length: 100}, (_, i) => `detail ${i}`).join('\n'));
  await until(() => app.lastFrame()?.includes('Details'));
  const screen = c.screen;
  assert(screen?.kind === 'document');
  app.stdin.write('\x1b[<64;10;10M\x1b[<65;10;10M');
  await until(() => screen.offset > 0);
  assert.equal(c.offset, null, 'a modal owns wheel scrolling');
  assert.equal(c.composer, draft);
  app.stdin.write('\x1b');
  await until(() => !c.screen);
  app.stdin.write('\x1b[200~[<64;10;10M\x1b[201~');
  await until(() => c.composer.text.endsWith('[<64;10;10M'));
});
