import {translate, type MessageKey} from '../i18n.js';

export function webviewHtml({script, style, nonce, cspSource, language}: {script: string; style: string; nonce: string; cspSource: string; language: string}): string {
  const t = (key: MessageKey) => translate(language, key);
    return `<!doctype html><html lang="${language}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src ${cspSource} data:; style-src ${cspSource}; script-src 'nonce-${nonce}';"><link rel="stylesheet" href="${style}"><title>Reuleaux</title></head><body>
      <header><div><strong>Reuleaux</strong><small id="environment">${t('Workspace core')}</small></div><nav><button data-command="actions" title="${t('Reuleaux actions')}">⋯</button><button data-command="openEditor" title="${t('Open in editor')}">↗</button><button data-command="newSession" title="${t('New session')}">＋</button><button data-command="sessions" title="${t('Session history')}">◷</button></nav></header>
      <section id="setup" hidden><h2 id="setup-title">${t('Connect your workspace')}</h2><p id="setup-message"></p><div class="actions"><button data-command="start" class="primary">${t('Start core')}</button><button data-command="install">${t('Install compatible core')}</button><button data-command="selectCore">${t('Select existing installation')}</button><button data-command="logs">${t('Show logs')}</button></div></section>
      <main id="transcript" aria-live="polite" aria-label="${t('Conversation')}"><div id="empty"><h2>${t('Start with your code.')}</h2><p>${t('Add selected code as context, or describe the task you want to complete.')}</p></div></main>
      <button id="new-output" hidden>↓ ${t('New output')}</button><section id="reviews" aria-label="${t('Pending reviews')}"></section><p id="notice" role="status" hidden></p>
      <footer id="drop-zone"><div id="attachments"></div><div class="composer"><textarea id="composer" aria-label="${t('Message')}" placeholder="${t('Describe a task, or paste an image or file…')}" rows="3"></textarea><div class="composer-actions"><button id="attach" title="${t('Add a local file')}">＋</button><button data-command="models" id="model" title="${t('Core actions and model settings')}">${t('Select model')}</button><span id="activity"></span><button data-command="stop" id="stop" title="${t('Stop current task')}">□</button><button id="send" class="primary" title="${t('Send')}">↑</button></div></div><div class="hint"><span>${t('Enter to send · Shift+Enter for a new line')}</span><span id="upload-hint">${t('Add instructions while a task is running')}</span></div></footer>
      <input id="files" type="file" multiple hidden><script nonce="${nonce}" src="${script}"></script></body></html>`;
}
