import {translate, type MessageKey} from '../i18n.js';

export function webviewHtml({script, style, nonce, cspSource, language}: {script: string; style: string; nonce: string; cspSource: string; language: string}): string {
  const t = (key: MessageKey) => translate(language, key);
  return `<!doctype html><html lang="${language}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src ${cspSource} data:; style-src ${cspSource}; script-src 'nonce-${nonce}';"><link rel="stylesheet" href="${style}"><title>Reuleaux</title></head><body>
    <header class="app-header"><div class="identity"><span class="brand-mark" data-icon="brand"></span><strong>Reuleaux</strong><small id="environment">${t('Workspace core')}</small></div><span id="activity" role="status"></span><nav aria-label="${t('Conversation')}"><button id="attention-jump" hidden data-icon="shield"><span></span></button><button id="overview-toggle" data-icon="settings" title="${t('Work overview')}" aria-label="${t('Work overview')}" aria-expanded="false" aria-controls="overview"></button><button data-command="sessions" data-icon="history" title="${t('Session history')}" aria-label="${t('Session history')}"></button><button data-command="newSession" data-icon="plus" title="${t('New session')}" aria-label="${t('New session')}"></button><button data-command="openEditor" data-icon="expand" title="${t('Open in editor')}" aria-label="${t('Open in editor')}"></button></nav></header>
    <section id="setup" hidden><h2 id="setup-title">${t('Connect your workspace')}</h2><p id="setup-message"></p><div class="actions"><button data-command="start" class="primary">${t('Start core')}</button><button data-command="install" aria-describedby="setup-install-hint">${t('Install compatible core')}</button><button data-command="selectCore">${t('Select existing installation')}</button><button data-command="configuration.open">${t('Check configuration')}</button><button data-command="logs">${t('Show logs')}</button></div><p id="setup-install-hint">${t('Uses the core bundled with this extension in a private environment on the workspace host. Switches to it after installation; external installations are kept. Dependencies may require a download.')}</p></section><section id="configuration-editor" hidden></section>
    <section id="overview" aria-label="${t('Work overview')}" hidden></section><main id="transcript" aria-label="${t('Conversation')}"><div id="empty"><div class="hero-mark" data-icon="brand"></div><small class="eyebrow">REULEAUX / ${t('Workspace')}</small><h1>${t('Make room for the next idea.')}</h1><p>${t('Describe a change. Bring your code. We will work through it together.')}</p><div class="starter-actions"><button data-action="goal.show" data-icon="goal">${t('Set a goal')}</button><button data-action="skills.show" data-icon="skills">${t('Explore skills')}</button><button data-command="sessions" data-icon="history">${t('Resume work')}</button></div></div><section id="reviews" aria-label="${t('Pending reviews')}"></section></main>
    <p id="notice" role="status" hidden></p>
    <footer id="drop-zone"><button id="new-output" hidden>↓ ${t('New output')}</button><div id="goal-strip" hidden></div><div class="composer-wrap"><section id="workbench" class="workbench" aria-label="${t('Commands')}" hidden></section><div class="composer"><div id="attachments"></div><textarea id="composer" aria-label="${t('Message')}" aria-expanded="false" aria-controls="command-list" aria-autocomplete="list" placeholder="${t('Message, or / for tools…')}" title="${t('Enter to send · Shift+Enter for a new line')}" rows="1"></textarea><div class="composer-actions"><button id="attach" data-icon="attach" title="${t('Add a local file')}" aria-label="${t('Add a local file')}"></button><button id="commands" data-icon="commands" title="${t('Commands and skills')}" aria-label="${t('Commands and skills')}" aria-haspopup="listbox"></button><button data-command="models" id="model" title="${t('Select model')}">${t('Select model')}</button><span class="composer-spacer"></span><button id="mode" data-action="mode.show" data-icon="mode" title="${t('Mode')}" aria-label="${t('Mode')}"></button><button id="permissions" data-action="approval.show" data-icon="shield" title="${t('Permissions')}" aria-label="${t('Permissions')}"></button><button data-command="stop" id="stop" data-icon="stop" title="${t('Stop current task')}" aria-label="${t('Stop current task')}"></button><button id="send" class="primary" data-icon="arrow" title="${t('Send')}" aria-label="${t('Send')}"></button></div></div></div><div class="hint"><span>${t('Enter to send · Shift+Enter for a new line')}</span><span id="upload-hint">${t('Add instructions while a task is running')}</span></div></footer>
    <input id="files" type="file" multiple hidden><script nonce="${nonce}" src="${script}"></script></body></html>`;
}
