"""Synthetic context messages carried through provider-compatible user roles."""

from __future__ import annotations

from html import escape
import re
from typing import Any, Mapping


SYNTHETIC_CONTEXT_METADATA_KEY = "_rc_synthetic_context"

RESERVED_CONTEXT_TAGS = frozenset(
    {
        "context_summary",
        "delegated_worker_data",
        "execution_state",
        "guidance_resolution",
        "inter_agent_message",
        "legacy_runtime_context",
        "project_context",
        "request_interrupted",
        "runtime_context_update",
        "runtime_instruction",
        "session_diagnostic",
        "subagent_conflict",
        "turn_interrupted",
    }
)

_TAG_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")


def _validate_tag(tag: str) -> str:
    if tag not in RESERVED_CONTEXT_TAGS or not _TAG_PATTERN.fullmatch(tag):
        raise ValueError(f"unsupported synthetic context tag: {tag}")
    return tag


def escape_context_payload(value: Any) -> str:
    """Escape untrusted payload text so it cannot close a reserved wrapper."""
    return escape(str(value), quote=False)


def escape_context_attribute(value: Any) -> str:
    """Escape one runtime-generated wrapper attribute value."""
    return escape(str(value), quote=True)


def mark_synthetic_user_message(
    content: str,
    *,
    tag: str,
    source: str,
) -> dict[str, Any]:
    """Mark an already wrapped runtime message for history-side semantics."""
    _validate_tag(tag)
    return {
        "role": "user",
        "content": content,
        SYNTHETIC_CONTEXT_METADATA_KEY: {"tag": tag, "source": source},
    }


def synthetic_user_message(
    tag: str,
    payload: Any,
    *,
    source: str,
    attributes: Mapping[str, Any] | None = None,
    escape_payload: bool = True,
) -> dict[str, Any]:
    """Wrap one application-generated context item as a synthetic user message."""
    tag = _validate_tag(tag)
    attrs = {"source": source, **dict(attributes or {})}
    rendered_attrs = " ".join(
        f'{key}="{escape(str(value), quote=True)}"'
        for key, value in sorted(attrs.items())
        if value is not None
    )
    body = escape_context_payload(payload) if escape_payload else str(payload)
    content = f"<{tag} {rendered_attrs}>\n{body}\n</{tag}>"
    return mark_synthetic_user_message(content, tag=tag, source=source)


def is_synthetic_context_message(message: Mapping[str, Any]) -> bool:
    """Return whether a history item was generated by the runtime."""
    marker = message.get(SYNTHETIC_CONTEXT_METADATA_KEY)
    return isinstance(marker, Mapping) and marker.get("tag") in RESERVED_CONTEXT_TAGS


def normalize_provider_message_roles(messages: list[dict]) -> list[dict]:
    """Guarantee that only the first provider message may use the system role.

    New runtime paths create tagged synthetic user messages directly.  This
    boundary conversion is deliberately fail-closed for legacy sessions and
    third-party hooks that still append later system messages.
    """
    normalized: list[dict] = []
    for index, message in enumerate(messages):
        item = dict(message)
        if item.get("role") == "system" and index != 0:
            content = str(item.get("content") or "")
            item = synthetic_user_message(
                "legacy_runtime_context",
                content,
                source="provider_boundary_system_migration",
            )
        for key in tuple(item):
            if str(key).startswith("_rc_"):
                item.pop(key, None)
        normalized.append(item)
    return normalized
