import * as vscode from 'vscode';
import assert from 'node:assert/strict';
import {mkdir, readFile, realpath, writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import type {activate} from '../../src/extension.js';
import {answerInteraction} from '../../src/core/interactions.js';
import {openWorkspaceFile} from '../../src/native/file-links.js';

async function until(predicate: () => unknown | Promise<unknown>, timeout = 10000): Promise<void> {
  const end = Date.now() + timeout;
  while (!await predicate()) {if (Date.now() > end) throw new Error('VS Code integration condition timed out.'); await delay(25);}
}
export async function run(): Promise<void> {
  const extension = vscode.extensions.getExtension<ReturnType<typeof activate>>('RC-CHN.reuleauxcoder');
  assert(extension, 'Extension is registered');
  const api = await extension.activate();
  const manifest = extension.packageJSON;
  assert.equal(manifest.extensionKind[0], 'workspace');
  assert.equal(manifest.contributes.viewsContainers.secondarySidebar[0].id, 'reuleaux');
  await vscode.commands.executeCommand('reuleaux.start');
  const session = await api.getSession(); const client = session.requireClient();
  const uri = vscode.Uri.joinPath(vscode.workspace.workspaceFolders![0].uri, 'example.py');
  let previousReviewUri: vscode.Uri | undefined;
  try {
    await session.commands.open('skills.show');
    await until(() => session.commands.surface?.panel?.view_type === 'skills' && !session.commands.surface.busy);
    const skill = session.commands.skill(session.commands.surface!.id, 'pptx');
    const bundled = await readFile(skill.details!.location, 'utf8');
    await api.dispatch('skill.open', {surfaceId: session.commands.surface!.id, name: 'pptx'});
    assert.equal(vscode.window.activeTextEditor!.document.uri.scheme, 'reuleaux-skill');
    assert.equal(vscode.window.activeTextEditor!.document.getText(), bundled);
    await vscode.commands.executeCommand('type', {text: 'blocked'});
    assert.equal(vscode.window.activeTextEditor!.document.getText(), bundled, 'Typing must not edit bundled instructions');
    await api.dispatch('skill.copy', {surfaceId: session.commands.surface!.id, name: 'pptx'});
    await until(() => session.commands.surface?.panel?.items.find(item => item.id === 'pptx')?.details?.source === 'project');
    const copied = vscode.window.activeTextEditor!.document;
    assert.equal(copied.uri.scheme, uri.scheme);
    assert.equal(await realpath(copied.uri.fsPath), await realpath(join(vscode.workspace.workspaceFolders![0].uri.fsPath, '.rcoder', 'skills', 'pptx', 'SKILL.md')));
    assert.equal(await readFile(skill.details!.location, 'utf8'), bundled);
    assert((await readFile(join(copied.uri.fsPath, '..', 'references', 'creation.md'), 'utf8')).includes('Presentation'));
    await assert.rejects(api.dispatch('skill.open', {surfaceId: session.commands.surface!.id, name: '../../config.yaml'}), /no longer available/);
    const staleSkillSurface = session.commands.surface!.id;
    await api.dispatch('skill.reload', {surfaceId: staleSkillSurface});
    await assert.rejects(api.dispatch('skill.open', {surfaceId: staleSkillSurface, name: 'pptx'}), /panel changed/);
    session.commands.close();
    console.log('PASS native readonly skill instructions, complete workspace customization and stale action guards');

    for (const newline of ['\n', '\r\n']) {
      await writeFile(uri.fsPath, `old = 1${newline}`);
      session.submit(`native-edit-${newline.length}`, 'edit', [], client.state.session_generation);
      await until(() => vscode.window.tabGroups.all.flatMap(group => group.tabs).some(tab => tab.input instanceof vscode.TabInputTextDiff));
      const input = vscode.window.tabGroups.all.flatMap(group => group.tabs).find(tab => tab.input instanceof vscode.TabInputTextDiff)!.input as vscode.TabInputTextDiff;
      assert.equal(input.modified.scheme, 'reuleaux-review');
      previousReviewUri = input.modified;
      assert.equal((await vscode.workspace.openTextDocument(input.original)).getText(), `old = 1${newline}`);
      assert.equal((await vscode.workspace.openTextDocument(input.modified)).getText(), `new = 1${newline}`);
      assert.equal(await readFile(uri.fsPath, 'utf8'), `old = 1${newline}`);
      await vscode.commands.executeCommand('reuleaux.approve', input.modified);
      await until(async () => (await readFile(uri.fsPath, 'utf8')) === `new = 1${newline}`);
      await until(() => !client.state.running);
      assert.equal(client.interactions.length, 0);
      // Expired editor buttons must never approve a later request.
      await vscode.commands.executeCommand('reuleaux.approve', input.modified);
      await vscode.window.tabGroups.close(vscode.window.tabGroups.all.flatMap(group => group.tabs).filter(tab => tab.input instanceof vscode.TabInputTextDiff));
      console.log(`PASS native readonly diff, approval and expired actions (${newline.length === 1 ? 'LF' : 'CRLF'})`);
    }

    const document = await vscode.workspace.openTextDocument(uri);
    let editor = await vscode.window.showTextDocument(document);
    assert.equal(document.eol, vscode.EndOfLine.CRLF);
    await editor.edit(edit => edit.replace(new vscode.Range(0, 0, document.lineCount, 0), 'old = 1\r\n'));
    await document.save();
    await editor.edit(edit => edit.replace(new vscode.Range(0, 0, document.lineCount, 0), 'old = 1\r\n# unsaved\r\n'));
    assert(document.isDirty);
    await until(() => client.peer.request('test.is_dirty', {path: uri.fsPath}));
    session.submit('dirty-edit', 'auto-edit', [], client.state.session_generation);
    await until(() => session.transcript.cells.some(cell => cell.text.includes('Unsaved editor changes')));
    assert.equal(await readFile(uri.fsPath, 'utf8'), 'old = 1\r\n');
    assert.equal(document.getText(), 'old = 1\r\n# unsaved\r\n');
    await document.save();
    await until(async () => !await client.peer.request('test.is_dirty', {path: uri.fsPath}));
    console.log('PASS real unsaved editor synchronization and automatic edit guard');

    await until(() => !client.state.running);
    session.submit('review-dirty-after-proposal', 'edit', [], client.state.session_generation);
    await until(() => client.interactions.some(item => item.kind === 'review'));
    const reviewId = client.interactions.find(item => item.kind === 'review')!.request.request_id;
    api.reviews.bind(client);
    await api.reviews.decide(true, previousReviewUri);
    assert(client.interactions.some(item => item.request.request_id === reviewId), 'An old editor URI must not approve a replacement review');
    const pendingEdit = new vscode.WorkspaceEdit(); pendingEdit.insert(uri, new vscode.Position(0, 0), '# changed after proposal\r\n');
    assert(await vscode.workspace.applyEdit(pendingEdit));
    await until(() => vscode.workspace.textDocuments.some(item => item.uri.toString() === uri.toString() && item.isDirty));
    assert(api.reviews.summaries().find(item => item.id === reviewId)?.dirty, JSON.stringify({proposal: api.reviews.summaries().find(item => item.id === reviewId)?.documents, dirty: vscode.workspace.textDocuments.filter(item => item.isDirty).map(item => item.uri.fsPath)}));
    await assert.rejects(api.reviews.decide(true, reviewId), /unsaved editor/);
    await assert.rejects(api.reviews.decide(true, reviewId, 'invented-scope'), /expired/);
    await api.reviews.saveAndRepropose(reviewId);
    await until(() => !client.state.running);
    assert((await readFile(uri.fsPath, 'utf8')).startsWith('# changed after proposal\r\nold = 1'));
    assert.equal(client.interactions.length, 0);
    console.log('PASS inline dirty-review handling rejects stale writes and validates grant IDs');

    editor = await vscode.window.showTextDocument(document);
    editor.selection = new vscode.Selection(1, 0, 1, 3);
    await vscode.commands.executeCommand('reuleaux.addContext', uri);
    assert(session.draftItems.some(item => item.text?.includes('old')));
    const collection = vscode.languages.createDiagnosticCollection('reuleaux-test');
    collection.set(uri, [new vscode.Diagnostic(new vscode.Range(0, 0, 0, 3), 'test diagnostic')]);
    const codeActions = await vscode.commands.executeCommand<vscode.CodeAction[]>('vscode.executeCodeActionProvider', uri, new vscode.Range(0, 0, 0, 3));
    assert(codeActions?.some(action => action.command?.command === 'reuleaux.fixDiagnostic'));
    collection.dispose();
    await vscode.commands.executeCommand('reuleaux.openEditor');
    await until(() => vscode.window.tabGroups.all.flatMap(group => group.tabs).some(tab => tab.input instanceof vscode.TabInputWebview));
    const tabs = vscode.window.tabGroups.all.flatMap(group => group.tabs).filter(tab => tab.input instanceof vscode.TabInputWebview);
    await vscode.window.tabGroups.close(tabs);
    assert.equal((await api.getSession()).requireClient(), client);
    assert(!client.peer.closed);
    console.log('PASS editor context, diagnostic action and view-independent connection');

    const folder = vscode.workspace.workspaceFolders![0];
    const reference = vscode.Uri.joinPath(folder.uri, 'docs', 'nested', 'My Notes 中文.md');
    await vscode.workspace.fs.createDirectory(vscode.Uri.joinPath(folder.uri, 'docs', 'nested'));
    await vscode.workspace.fs.writeFile(reference, Buffer.from('one\ntwo\nthree\n'));
    await openWorkspaceFile(folder, 'docs/nested/My%20Notes%20%E4%B8%AD%E6%96%87.md:2:2');
    assert.equal(vscode.window.activeTextEditor!.document.uri.toString(), reference.toString());
    assert.equal(vscode.window.activeTextEditor!.selection.start.line, 1);
    assert.equal(vscode.window.activeTextEditor!.selection.start.character, 1);
    await openWorkspaceFile(folder, `${reference.fsPath}#L2-L3`);
    assert.equal(vscode.window.activeTextEditor!.selection.end.line, 2);
    assert.equal(vscode.window.activeTextEditor!.selection.end.character, 5);
    await assert.rejects(openWorkspaceFile(folder, '../outside.md'), /outside/);
    await assert.rejects(openWorkspaceFile(folder, 'command:workbench.action.closeWindow'), /Invalid file/);
    await assert.rejects(openWorkspaceFile(folder, 'missing.md'), /not found/);
    assert.equal(vscode.window.activeTextEditor!.document.uri.toString(), reference.toString());
    console.log('PASS native workspace file links, nested Unicode paths and line selections');

    await until(() => !client.state.running);
    session.submit('native-question', 'question', [], client.state.session_generation);
    await until(() => client.interactions.some(item => item.kind === 'input_text'));
    assert(session.snapshot().interactions![0].secret);
    answerInteraction(client, {id: client.interactions[0].request.request_id, value: 'inline answer'});
    await until(() => !client.state.running);
    session.submit('cancel-question', 'question', [], client.state.session_generation);
    await until(() => client.interactions.some(item => item.kind === 'input_text'));
    await client.interrupt();
    await until(() => !client.interactions.length && !client.state.running);
    console.log('PASS inline secret answer and backend cancellation');
    await session.shutdown();
    const configFile = vscode.Uri.joinPath(folder.uri, 'configuration 中文.yaml');
    const launcher = vscode.Uri.joinPath(folder.uri, 'configuration-launcher.py');
    const settings = vscode.workspace.getConfiguration('reuleaux', folder.uri);
    const originalArgs = settings.get<string[]>('coreArguments', []);
    const home = join(folder.uri.fsPath, 'test-home');
    await mkdir(join(home, '.rcoder'), {recursive: true});
    const globalText = '# global defaults\napp:\n  api_key: native-test\n  model: global-model\n';
    await writeFile(join(home, '.rcoder', 'config.yaml'), globalText);
    await writeFile(launcher.fsPath, "import os, sys, runpy\nfrom pathlib import Path\nos.environ['HOME'] = str(Path(__file__).parent / 'test-home')\nos.environ['USERPROFILE'] = os.environ['HOME']\nif '--config-management-stdio' in sys.argv:\n from reuleauxcoder.interfaces.launcher import main\n raise SystemExit(main())\nfrom reuleauxcoder.services.config.loader import ConfigLoader\nConfigLoader(Path(sys.argv[sys.argv.index('--config') + 1])).load()\nrunpy.run_path(" + JSON.stringify(originalArgs[0]) + ", run_name='__main__')\n");
    await settings.update('coreArguments', [launcher.fsPath, '--config', configFile.fsPath], vscode.ConfigurationTarget.WorkspaceFolder);
    await writeFile(configFile.fsPath, 'app: [broken');
    await assert.rejects(api.dispatch('start'));
    assert.equal(session.phase, 'failed');
    await api.dispatch('configuration.open');
    assert.equal(session.configuration.state!.valid, false);
    assert.equal((await session.configuration.process.client!.inspect()).runtime, null);
    await api.dispatch('configuration.file', {scope: 'explicit'});
    editor = vscode.window.activeTextEditor!;
    assert.equal(editor.document.uri.path.split('/').at(-1), 'configuration 中文.yaml');
    assert.equal(editor.document.uri.scheme, folder.uri.scheme);
    const fullRange = () => new vscode.Range(new vscode.Position(0, 0), editor.document.positionAt(editor.document.getText().length));
    const content = '# keep comments and CRLF\r\nui:\r\n  verbosity: debug\r\n';
    await editor.edit(edit => {edit.setEndOfLine(vscode.EndOfLine.CRLF); edit.replace(fullRange(), content);});
    await api.dispatch('configuration.check');
    assert(session.configuration.state!.validation!.valid);
    assert(session.configuration.state!.validation!.buffer_check);
    assert.equal(await readFile(configFile.fsPath, 'utf8'), 'app: [broken');
    await assert.rejects(api.dispatch('configuration.restart'), /Save configuration files/);
    await api.dispatch('configuration.save');
    assert.equal(await readFile(configFile.fsPath, 'utf8'), content);
    assert.equal(await readFile(join(home, '.rcoder', 'config.yaml'), 'utf8'), globalText);
    assert.equal(session.phase, 'failed', 'Saving must not automatically restart');
    await api.dispatch('configuration.restart');
    assert.equal(session.phase, 'ready');
    const runningClient = session.requireClient();
    await api.dispatch('configuration.open');
    // A hand-saved invalid file must fail preflight without stopping the live core.
    await editor.edit(edit => edit.replace(fullRange(), 'ui:\n  verbositty: debug\n'));
    await editor.document.save();
    await assert.rejects(api.dispatch('configuration.restart'), /Fix configuration errors/);
    assert.equal(session.phase, 'ready'); assert.equal(session.client, runningClient); assert(!runningClient.peer.closed);
    assert.equal(session.configuration.state!.diagnostics[0].code, 'unknown_field');
    await api.dispatch('configuration.file', {scope: 'user'});
    assert.equal(vscode.window.activeTextEditor!.document.uri.fsPath, join(home, '.rcoder', 'config.yaml'));
    assert.equal(vscode.window.activeTextEditor!.document.getText(), globalText);
    console.log('PASS native config buffers, global inheritance, CRLF/comment preservation and restart preflight');
  } finally {if (!client.peer.closed) await client.interrupt(); await session.configuration.close(); await session.shutdown();}
}
